server.host: "0.0.0.0"

monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.hosts: "${ELASTICSEARCH_HOST}"

elasticsearch.password: "${ELASTIC_PASSWORD}"
elasticsearch.serviceAccountToken: "${ELASTIC_SERVICE_ACCOUNT_TOKEN}"

xpack.encryptedSavedObjects.encryptionKey: "5a8f09b4c24d6a5678e5a9e1bcd892cd"
