network.host: 0.0.0.0

cluster.name: 'main cluster'
discovery.seed_hosts: []
cluster.initial_master_nodes: ["elasticsearch"]

bootstrap.memory_lock: 'true'

xpack.security.enabled: false
xpack.security.authc.api_key.enabled: false
xpack.security.authc.token.enabled: false

xpack.security.authc.anonymous.username: ""
xpack.security.authc.anonymous.roles: []
xpack.security.authc.anonymous.authz_exception: true
